plugins { id 'com.android.application' }
android {
    namespace 'dev.tommy.daylightpilot'
    compileSdk 35
    defaultConfig {
        applicationId 'dev.tommy.daylightpilot'
        minSdk 30
        targetSdk 35
        versionCode 4
        versionName '0.4'
        testInstrumentationRunner 'dev.tommy.daylightpilot.LoadingPreview'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
